# Start App

services:
  node:
    container_name: express-store-front
    image: express-store-front:nvm22
    build:
      context: ../../../../docker/node
    environment:
      - NODE_VERSION=22
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - C:/host/var-www/html/infnet/express-store-front:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "5173-5178:5173-5178"
