# Start App

services:
  node:
    container_name: express-store
    image: paulohbsouzaa/node:nvm22
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_COMMANDS=npm install && npm run dev
    volumes:
      - C:/host/var-www/html/infnet/express-store:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"